### PR TITLE
Fix OpenNebula user autocreate with VOMS credentials

### PR DESCRIPTION
**Pull request by Misenko**
Description in commit messages.

### CODE REVIEW

**Comment by Misenko** [comment]
I forgot to fix tests. Bear with me...

**Comment by Misenko** [comment]
Now we're cooking 😎

**Comment by Misenko** [comment]
It's used for the password and it's also available in the metadata under `IDENTITY`. Or did you mean something else?

**Comment by arax** [comment]
I remember we had a discussion about hashing DNs, but I don't remember why. Can you refresh my memory a bit?

**Comment by Misenko** [comment]
In this case? Because DNs have whitespaces and you cannot have a whitespace in passwords in OpenNebula. And with id, which is used for user's name, probably the same reason.

**Comment by arax** [comment]
Ok, that rings a bell :-) The problem I see here is that other tools (at least `oneacct-export` and `rOCCI-server`) are using `USER['IDENTITY']` in ways that are incompatible with its new hashed content. Can we keep user metadata intact while hashing ID (and password)?

**Comment by Misenko** [comment]
It depends. Does it matter what is saved as a password? If not, I can do the hashing when creating a user no matter what. But this would hash OIDC identifier as well. This would leave `IDENTITY` intact.

**Comment by Misenko** [comment]
OIDC identity I mean. The thing that's used for a password. In case of OIDC it's `OIDC_sub` variable.

**Comment by arax** [comment]
Well, it depends on how you look up existing users when generating scoped tokens. I believe that no one else interacts with this value in OpenNebula at this level. If the auth driver is set to `remote`, you can do whatever you like. On a related note, are you distinguishing between users created from VOMS and OIDC or just relying on the credentials (name? password?) not matching? That's probably the most important factor here.

**Comment by Misenko** [comment]
I look up users based on their name (`OIDC_sub` for OIDC and hashed DN for VOMS). And no, I don't distinguish between OIDC and VOMS users.

**Comment by arax** [comment]
Then you can hash passwords at will :-)

**Comment by Misenko** [comment]
Ok, I think this should work. What do you think?

**Pull request merged**
